name: "s3"

x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

services:
  minio:
    # for more information about this image checkout:
    # https://github.com/11notes/docker-minio
    image: "11notes/minio:2025.10.15"
    hostname: "minio"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
      MINIO_ROOT_CA_KEY_FILE: "/run/secrets/ca_key"
      MINIO_ROOT_CA_CRT_FILE: "/run/secrets/ca_crt"
      MINIO_ROOT_PASSWORD_FILE: "/run/secrets/password"
    command: "/mnt"
    volumes:
      - "minio.ssl:/minio/ssl"
      - "minio.var:/mnt"
    tmpfs:
      # needed for read-only
      - "/run/secrets:uid=1000,gid=1000"
    secrets:
      - "ca_key"
      - "ca_crt"
      - "password"
    networks:
      backend:
    restart: "always"

  minio-console:
    depends_on:
      minio:
        condition: "service_healthy"
        restart: true
    image: "11notes/minio-console:1.8.1"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
      MINIO_CONSOLE_MINIO_URL: "https://minio:9000"
      MINIO_CONSOLE_MINIO_PASSWORD_FILE: "/run/secrets/password"
      MINIO_CONSOLE_PASSWORD_FILE: "/run/secrets/console_password"
      MC_INSECURE: true
    ports:
      - "3000:9090/tcp"
    volumes:
      - "minio-console.etc:/minio-console/etc"
      - "minio-console.ssl:/minio-console/ssl"
    tmpfs:
      # needed for read-only
      - "/run/secrets:uid=1000,gid=1000"
    secrets:
      - "ca_key"
      - "ca_crt"
      - "password"
      - "console_password"
    networks:
      frontend:
      backend:
    restart: "always"

volumes:
  minio.ssl:
  minio.var:
  minio-console.etc:
  minio-console.ssl:

networks:
  frontend:
  backend:
    internal: true

secrets:
  ca_key:
    file: "./ca.key.txt"
  ca_crt:
    file: "./ca.crt.txt"
  password:
    file: "./password.txt"
  console_password:
    file: "./console_password.txt"